#! /bin/sh

export MONITOR=$(xrandr -q | grep primary | cut -d' ' -f1)
export MONITORS=( $(xrandr -q | grep ' connected' | cut -d' ' -f1) )
MONITOR=${MONITOR:-${MONITORS[0]}}

# Only have workspaces for primary monitor
for monitor in $MONITORS; do
  bspc monitor $monitor -d 0
done
bspc monitor $MONITOR -d {1,2,3,4,5}

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# bspc rule -a firefox desktop='^2'
# bspc rule -a discord desktop='^6'
# bspc rule -a mailspring desktop='^6'
# bspc rule -a Steam desktop='^9'


# Border
bspc config focused_border_color        "#DDB6F2"
bspc config normal_border_color         "#4c566a"
bspc config active_border_color         "#4c566a"

#
# Autostart
# picom &
# nitrogen &
#~/.config/bspwm/autostart
